"""Crypto-layer tests, including known-answer vectors.

On the provenance of the vectors below -- this distinction matters, because a
test that only checks our code against itself proves very little:

  * The AES-256-GCM vectors ARE independent. They are Test Cases 13 and 14
    from the McGrew & Viega GCM specification that NIST SP 800-38D adopted.
    Passing them is real evidence the primitive is correct.

  * The Argon2id and HKDF vectors are NOT independent. They are golden values
    generated by this library and pinned here. They catch drift in our
    parameters, encoding or output length -- not correctness of Argon2 itself.
    The RFC 9106 vector cannot be used: it requires the optional secret-key
    and associated-data inputs, and argon2-cffi's raw API does not expose
    them. Correctness of the primitive is delegated to argon2-cffi's own
    suite, which is the right place for it.
"""

import pytest
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from hecate.crypto import aead, kdf, rng


# --- AES-256-GCM known-answer tests (independent, from the GCM spec) -------


def test_kat_gcm_test_case_13_empty_plaintext():
    key, nonce = bytes(32), bytes(12)
    assert AESGCM(key).encrypt(nonce, b"", None).hex() == (
        "530f8afbc74536b9a963b4f1c4cb738b"
    )


def test_kat_gcm_test_case_14_one_zero_block():
    key, nonce = bytes(32), bytes(12)
    assert AESGCM(key).encrypt(nonce, bytes(16), None).hex() == (
        "cea7403d4d606b6e074ec5d3baf39d18"  # ciphertext
        "d0d1c8a799996bf0265b98b5d48ab919"  # tag
    )


# --- Argon2id / HKDF golden vectors (drift guards) ------------------------


def test_golden_argon2id_derivation():
    derived = kdf.derive_master_key(
        b"correct horse battery staple", b"\x02" * 16, kdf.FAST_ARGON2_FOR_TESTS
    )
    assert derived.hex() == (
        "cbd00be884100538f23a5d46d530f18bbe8d3b918b798fc0ba04a0705a44c330"
    )


def test_golden_hkdf_recovery_derivation():
    derived = kdf.derive_recovery_key(b"\x07" * 20, b"\x03" * 16)
    assert derived.hex() == (
        "4848d072c7c68f697695a3d2780d055d69374fa1d6063e742b9e36cfb83db5f4"
    )


def test_derivation_is_deterministic_and_salt_sensitive():
    params = kdf.FAST_ARGON2_FOR_TESTS
    a = kdf.derive_master_key(b"pw", b"\x01" * 16, params)
    b = kdf.derive_master_key(b"pw", b"\x01" * 16, params)
    c = kdf.derive_master_key(b"pw", b"\x02" * 16, params)
    assert a == b
    assert a != c


def test_derivation_changes_with_cost_parameters():
    salt = b"\x01" * 16
    weak = kdf.derive_master_key(b"pw", salt, kdf.Argon2Params(1, 8 * 1024, 1))
    strong = kdf.derive_master_key(b"pw", salt, kdf.Argon2Params(2, 8 * 1024, 1))
    assert weak != strong


def test_derive_master_key_rejects_str_password():
    with pytest.raises(TypeError):
        kdf.derive_master_key("not bytes", b"\x01" * 16, kdf.FAST_ARGON2_FOR_TESTS)


def test_argon2_params_reject_unknown_algorithm():
    with pytest.raises(ValueError):
        kdf.Argon2Params.from_dict(
            {"algorithm": "scrypt", "time_cost": 1, "memory_cost": 8, "parallelism": 1}
        )


# --- AEAD wrapper ---------------------------------------------------------


def test_encrypt_decrypt_round_trip():
    key = rng.generate_data_key()
    nonce, ct = aead.encrypt(key, b"attack at dawn", b"header")
    assert aead.decrypt(key, nonce, ct, b"header") == b"attack at dawn"


def test_nonce_is_fresh_on_every_call():
    key = rng.generate_data_key()
    nonces = {aead.encrypt(key, b"same", b"")[0] for _ in range(50)}
    assert len(nonces) == 50


def test_decrypt_fails_with_wrong_key():
    nonce, ct = aead.encrypt(rng.generate_data_key(), b"secret", b"")
    with pytest.raises(aead.DecryptionError):
        aead.decrypt(rng.generate_data_key(), nonce, ct, b"")


def test_decrypt_fails_when_ciphertext_is_tampered():
    key = rng.generate_data_key()
    nonce, ct = aead.encrypt(key, b"secret", b"")
    flipped = bytearray(ct)
    flipped[0] ^= 0x01
    with pytest.raises(aead.DecryptionError):
        aead.decrypt(key, nonce, bytes(flipped), b"")


def test_decrypt_fails_when_aad_differs():
    key = rng.generate_data_key()
    nonce, ct = aead.encrypt(key, b"secret", b"header-v1")
    with pytest.raises(aead.DecryptionError):
        aead.decrypt(key, nonce, ct, b"header-v2")


# --- recovery key encoding ------------------------------------------------


def test_recovery_key_round_trip():
    secret = rng.generate_recovery_secret()
    assert rng.parse_recovery_key(rng.format_recovery_key(secret)) == secret


def test_recovery_key_is_tolerant_of_user_formatting():
    secret = rng.generate_recovery_secret()
    text = rng.format_recovery_key(secret)
    assert rng.parse_recovery_key(text.lower().replace("-", " ")) == secret


def test_recovery_key_rejects_garbage():
    with pytest.raises(ValueError):
        rng.parse_recovery_key("not-a-valid-key!!")
